package objetos;

public enum Conjunto{
    PRIMEROS_DOCE, SEGUNDOS_DOCE, TERCEROS_DOCE, UNO_DIECIOCHO, DIECINUEVE_TRENTAYSEIS, FILA_1, 
    FILA_2, FILA_3, CERO, DOBLE_CERO, PAR, IMPAR, ROJO, NEGRO 
}
